/*1035. Password (20)
时间限制
400 ms
内存限制
65536 kB
代码长度限制
16000 B
判题程序
Standard
作者
CHEN, Yue
To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.

Input Specification:

Each input file contains one test case. Each case contains a positive integer N (<= 1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.

Output Specification:

For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line "There are N accounts and no account is modified" where N is the total number of accounts. However, if N is one, you must print "There is 1 account and no account is modified" instead.

Sample Input 1:

3
Team000002 Rlsp0dfa
Team000003 perfectpwd
Team000001 R1spOdfa
Sample Output 1:
2
Team000002 RLsp%dfa
Team000001 R@spodfa
Sample Input 2:
1
team110 abcdefg332
Sample Output 2:
There is 1 account and no account is modified
Sample Input 3:
2
team110 abcdefg222
team220 abcdefg333
Sample Output 3:
There are 2 accounts and no account is modified*/

#include <cstdio>
#include <cstring>

using namespace std;

const int maxn = 2510;
const int INF = 0xfffffff;

struct student {
    char id[20], password[20];
    bool isModified;

    student() {
        isModified = false;
    }
} s[maxn], fin[maxn];

bool Deal(char s[]) {
    int len = strlen(s);
    int flag = false;
    for (int i = 0; i < len; ++i) {
        if (s[i] == '1') {
            s[i] = '@';
            flag = true;
        }
        if (s[i] == '0') {
            s[i] = '%';
            flag = true;
        }
        if (s[i] == 'O') {
            s[i] = 'o';
            flag = true;
        }
        if (s[i] == 'l') {
            s[i] = 'L';
            flag = true;
        }


    }
    return flag;
}

int main() {
    freopen("C:\\Users\\71000\\CLionProjects\\demo\\data.in", "r", stdin);
    int n, m = 0;
    scanf("%d", &n);
    if(n==0){
        printf("There are 0 accounts and no account is modified");
        return 0;
    }
    for (int i = 0; i < n; ++i) {
        scanf("%s %s", s[i].id, s[i].password);
        if (Deal(s[i].password) == true) {
            s[i].isModified == true;
            fin[m++] = s[i];
        }
    }
    if (m == 0) {
        if (n <=1)
            printf("There is %d account and no account is modified", n);
        else
            printf("There is %d accounts and no account is modified", n);
    } else {
        printf("%d\n", m);
        for (int i = 0; i < m; ++i) {
            printf("%s %s\n", fin[i].id, fin[i].password);
        }
    }

    return 0;
}
